### ISSUE TITLE
Scenario consistency promise hangs tests (seemingly) at random

### ISSUE THREAD

**Issue by pospi** [maackle/hc-playbook#11]
I've been hitting up against these hangs indeterminately, and perhaps have figured out the failure condition. My guess is that if no alterations have been performed on the DHT, then no signal is ever sent to indicate that consistency has been reached since no inconsistent state occurred to begin with.

This manifests in [these two tests](https://github.com/holo-rea/holo-rea/blob/9d710a4/test/core-architecture/test_update_behavior.js), where the first test is essentially a noop whilst the second actually causes an entry update.

Unsure what can be done about this- perhaps tracking the internal synchronisation state of the DHT and resolving `s.consistent()` immediately if no write operations have been performed. Sounds like a complex cache invalidation problem :/

**Comment by maackle** [comment]
@pospi if you wait 60 seconds, does it tell you what it's waiting for? You should either get a "hachiko timeout", or a message that the zome function itself timed out after 60 seconds. If not, that's even more unusual...

**Comment by pospi** [comment]
It's the hachiko timeout that I'm seeing.

**Comment by maackle** [comment]
Can you post the full hachiko timeout message that includes what is being waited for?

**Comment by pospi** [comment]
All yours!

```
info: [C] 2019-06-23 11:26:21 ThreadId(1):observation-3: debug/actions/call_zome_fn: Validating call: ZomeFnCall { id: ProcessUniqueId { prefix: 7, offset: 7 }, zome_name: "main", cap: CapabilityRequest { cap_token: HashString("QmQ693LzmUuXHzRJHFgQypGWxtGr9rMRWsE9WyuVLRbkSQ"), provenance: Provenance(HashString("HcSCjHmVuZKrg7rgvrz7uBxHpkf3ncmvfnWU3HFgzYjd9w7rxihu4Bh3ztug9si"), Signature("i79pi3wj+JWPbLJD+RZF1ed0n6wymCCcC4n5S6jvafROQFSGAz9sdEMaB+LtY/amFdcuRhioR60UQt0hhRzABg==")) }, fn_name: "get_event", parameters: JsonString("{\"address\":\"QmWzsNa3VG8XSdPtqmMhqm6YLjsAFRQM5NnuiPFcPqyNUE\"}") }

info: [C] 2019-06-23 11:26:21 ThreadId(1):observation-3: debug/actions/call_zome_fn: executing call: ZomeFnCall { id: ProcessUniqueId { prefix: 7, offset: 7 }, zome_name: "main", cap: CapabilityRequest { cap_token: HashString("QmQ693LzmUuXHzRJHFgQypGWxtGr9rMRWsE9WyuVLRbkSQ"), provenance: Provenance(HashString("HcSCjHmVuZKrg7rgvrz7uBxHpkf3ncmvfnWU3HFgzYjd9w7rxihu4Bh3ztug9si"), Signature("i79pi3wj+JWPbLJD+RZF1ed0n6wymCCcC4n5S6jvafROQFSGAz9sdEMaB+LtY/amFdcuRhioR60UQt0hhRzABg==")) }, fn_name: "get_event", parameters: JsonString("{\"address\":\"QmWzsNa3VG8XSdPtqmMhqm6YLjsAFRQM5NnuiPFcPqyNUE\"}") }
2019-06-23 11:26:21 ThreadId(1):observation-3: debug/actions/call_zome_fn: awaiting for future call result of ZomeFnCall { id: ProcessUniqueId { prefix: 7, offset: 7 }, zome_name: "main", cap: CapabilityRequest { cap_token: HashString("QmQ693LzmUuXHzRJHFgQypGWxtGr9rMRWsE9WyuVLRbkSQ"), provenance: Provenance(HashString("HcSCjHmVuZKrg7rgvrz7uBxHpkf3ncmvfnWU3HFgzYjd9w7rxihu4Bh3ztug9si"), Signature("i79pi3wj+JWPbLJD+RZF1ed0n6wymCCcC4n5S6jvafROQFSGAz9sdEMaB+LtY/amFdcuRhioR60UQt0hhRzABg==")) }, fn_name: "get_event", parameters: JsonString("{\"address\":\"QmWzsNa3VG8XSdPtqmMhqm6YLjsAFRQM5NnuiPFcPqyNUE\"}") }

info: [C] 2019-06-23 11:26:21 ThreadId(1):observation-3: log/get_links: invoke_get_links called with GetLinksArgs { entry_address: HashString("QmWzsNa3VG8XSdPtqmMhqm6YLjsAFRQM5NnuiPFcPqyNUE"), link_type: Some("vf_economic_event_fulfills"), tag: Some("fulfills"), options: GetLinksOptions { status_request: Live, headers: false, timeout: Timeout(60000) } }

info: [C] 2019-06-23 11:26:21 ThreadId(1):observation-3: debug/net/handle: HandleFetchMeta: FetchMetaData { dna_address: HashString("QmaqXX3LBSJDTU5vvBWqQHahGhzwMCeJoyRWZiehFeGhta"), request_id: "puid-2a-0", requester_agent_id: "HcSCjHmVuZKrg7rgvrz7uBxHpkf3ncmvfnWU3HFgzYjd9w7rxihu4Bh3ztug9si", entry_address: HashString("QmWzsNa3VG8XSdPtqmMhqm6YLjsAFRQM5NnuiPFcPqyNUE"), attribute: "link__vf_economic_event_fulfills__fulfills" }

info: [C] debug/reduce/get_links: Responding to GET LINKS request from HcSCjHmVuZKrg7rgvrz7uBxHpkf3ncmvfnWU3HFgzYjd9w7rxihu4Bh3ztug9si with []

info: [C] debug/reduce/handle_get_links_result: Got response from HcSCjHmVuZKrg7rgvrz7uBxHpkf3ncmvfnWU3HFgzYjd9w7rxihu4Bh3ztug9si: [Array([])]
2019-06-23 11:26:21 ThreadId(1):observation-3: debug/net/handle: FetchMetaResult: FetchMetaResultData { dna_address: HashString("QmaqXX3LBSJDTU5vvBWqQHahGhzwMCeJoyRWZiehFeGhta"), request_id: "puid-2a-0", requester_agent_id: "HcSCjHmVuZKrg7rgvrz7uBxHpkf3ncmvfnWU3HFgzYjd9w7rxihu4Bh3ztug9si", provider_agent_id: "HcSCjHmVuZKrg7rgvrz7uBxHpkf3ncmvfnWU3HFgzYjd9w7rxihu4Bh3ztug9si", entry_address: HashString("QmWzsNa3VG8XSdPtqmMhqm6YLjsAFRQM5NnuiPFcPqyNUE"), attribute: "link__vf_economic_event_fulfills__fulfills", content_list: [Array([])] }

info: [C] 2019-06-23 11:26:30 ThreadId(1):observation-3: debug/scheduled_jobs: tick

info: [C] 2019-06-23 11:26:40 ThreadId(1):observation-3: debug/scheduled_jobs: tick

info: [C] 2019-06-23 11:26:50 ThreadId(1):observation-3: debug/scheduled_jobs: tick

info: [C] 2019-06-23 11:27:00 ThreadId(1):observation-3: debug/scheduled_jobs: tick

info: [C] 2019-06-23 11:27:10 ThreadId(1):observation-3: debug/scheduled_jobs: tick

info: [C] 2019-06-23 11:27:20 ThreadId(1):observation-3: debug/scheduled_jobs: tick

error: Test failed while running: "zome call timed out after 60 seconds: observation-3/main/get_event"
not ok 2 (unnamed assert)
  ---
    operator: fail
    at: run.catch (/home/pospi/projects/holo-rea/oce-holo/node_modules/@holochain/diorama/lib/executors.js:18:19)
    stack: |-
      Error: (unnamed assert)
          at Test.assert [as _assert] (/home/pospi/projects/holo-rea/oce-holo/test/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/pospi/projects/holo-rea/oce-holo/test/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/home/pospi/projects/holo-rea/oce-holo/test/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/home/pospi/projects/holo-rea/oce-holo/test/node_modules/tape/lib/test.js:76:32)
          at run.catch (/home/pospi/projects/holo-rea/oce-holo/node_modules/@holochain/diorama/lib/executors.js:18:19)
  ...
# updates with fields nulled remove original value
info: Test over, waiting for Waiter to flush...
info: [C] 2019-06-23 11:27:30 ThreadId(1):observation-3: debug/scheduled_jobs: tick

vvvv    hachiko warning    vvvv
a hachiko callback has been waiting for 16 seconds with no change
Still waiting on the following 1 signal(s):
[ { event: '{"ReturnZomeFunctionResult":{"prefix":7,"offset":7}}',
    sourceNode: 'observation',
    targetNode: 'observation' } ]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
info: [C] 2019-06-23 11:27:40 ThreadId(1):observation-3: debug/scheduled_jobs: tick

info: [C] 2019-06-23 11:27:50 ThreadId(1):observation-3: debug/scheduled_jobs: tick

info: [C] 2019-06-23 11:28:00 ThreadId(1):observation-3: debug/scheduled_jobs: tick

info: [C] 2019-06-23 11:28:10 ThreadId(1):observation-3: debug/scheduled_jobs: tick

info: [C] 2019-06-23 11:28:20 ThreadId(1):observation-3: debug/scheduled_jobs: tick

vvvv  hachiko timed out!  vvvv
Still waiting on the following 1 signal(s):
[ { event: '{"ReturnZomeFunctionResult":{"prefix":7,"offset":7}}',
    sourceNode: 'observation',
    targetNode: 'observation' } ]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/pospi/projects/holo-rea/oce-holo/node_modules/@holochain/hachiko/lib/waiter.js:28
                throw new Error("hachiko timeout!!");
                ^

Error: hachiko timeout!!
    at Timeout._onTimeout (/home/pospi/projects/holo-rea/oce-holo/node_modules/@holochain/hachiko/lib/waiter.js:28:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
```

**Comment by maackle** [comment]
@pospi, sorry for missing your reply for so long.

When this happens, it means that the zome function itself is hanging. The fact that hachiko is waiting for `ReturnZomeFunctionResult` means that the zome function itself never returned. You can also see this by the notice that the zome function itself timed out:

> `zome call timed out after 60 seconds: observation-3/main/get_event`

We have seen this before, and it corresponded with a bug in Holochain, and that may be the case here. If you are sure you're not doing anything that would cause your function to crash or not terminate, could you point me to the actual code that causes this failure? This may wind up being an HC Core issue.

**Comment by pospi** [comment]
Looping back on this with further info... see https://github.com/holochain/holochain-rust/issues/1662
