### ISSUE TITLE
Config generation broken in 0.3.0-rc.2

### ISSUE THREAD

**Issue by pospi** [maackle/hc-playbook#21]
It looks like the config generation in `0.3.0` alpha is broken. Reverting to `0.2.0-rc.1` fixed the issue, though I'm unsure whether the older version works with current `holochain-rust` as I still have some test failures to work through.

```
$ cat /tmp/tmp.ze3agIDHaB/hc-diorama-sB9K4C/conductor-config.toml
[object Promise]
```

For completeness, this is what log output currently looks like when running a single tape test:

```
info: Test over, waiting for Waiter to flush...
info: Using config file at /tmp/tmp.ze3agIDHaB/hc-diorama-sB9K4C/conductor-config.toml
info: Using holochain binary at /nix/store/5dsdc60gfc51a0vabbsfv1ivqw2lv0p8-holochain/bin/holochain

info: [C] Using config path: /tmp/tmp.ze3agIDHaB/hc-diorama-sB9K4C/conductor-config.toml
Error while trying to boot from config: IoError("Error loading configuration: expected a right bracket, found an identifier at line 1")

info: conductor exited with code 0
not ok 1 test exited without ending
  ---
    operator: fail
    at: process.<anonymous> (/home/pospi/projects/holo-rea/oce-holo/test/node_modules/tape/index.js:90:19)
    stack: |-
      Error: test exited without ending
          at Test.assert [as _assert] (/home/pospi/projects/holo-rea/oce-holo/test/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/pospi/projects/holo-rea/oce-holo/test/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/home/pospi/projects/holo-rea/oce-holo/test/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/home/pospi/projects/holo-rea/oce-holo/test/node_modules/tape/lib/test.js:76:32)
          at Test._exit (/home/pospi/projects/holo-rea/oce-holo/test/node_modules/tape/lib/test.js:190:14)
          at Test.bound [as _exit] (/home/pospi/projects/holo-rea/oce-holo/test/node_modules/tape/lib/test.js:76:32)
          at process.<anonymous> (/home/pospi/projects/holo-rea/oce-holo/test/node_modules/tape/index.js:90:19)
          at process.emit (events.js:193:13)
  ...
```

**Comment by rlkelly** [comment]
having this same issue while going through the "Hello Test Tutorial"

**Comment by rlkelly** [comment]
I downgraded to `"@holochain/diorama": "0.2.0-rc.1"` and it worked.  It believe it would be worth noting in the docs which version to use
